custom_collections:
  ids:
    'lrGRACE_NIMS':
     's3://veda-data-store-staging/EIS/zarr/gia/SESAW/SlrGRACE_NIMS.zarr'
    'GRACE_0.5_DEGREE':
     's3://dh-eis-sealevel-usw2-shared/zarr/GRACE/GSFC/gsfc.glb_.200204_202112_rl06v2.0_obp-ice6gd_halfdegree.zarr'

# Must be a bounding box
bounds:
  -  [-76.6, 38.8, -76.5, 38.9]

# Must be in YYYY-MM-DD
time_bounds:
  start: '2019-05-18'
  end: '2019-06-18'

title:
  title: '# EIS General Dashboard'
  subtitle: '## Alpha version: 0.3.0'

# MUST BE 'INFO', 'WARN', 'DEBUG'
log_level: 'INFO'
log_dir: '.'
